project:
  type: website
  output-dir: docs

website:
  title: "Eugene's Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/jinxyou
      - icon: linkedin
        href: https://linkedin.com/in/jinxyou
format:
  html:
    theme: cosmo
    css: styles.css



